
server:  port: 8888
  
spring:
  cloud:    config:      server:        git:          uri: https://github.com/williammian/microservices-repo
          search-paths: fornecedorms
          default-label: main