
server:  port: 8888
  
spring:
  cloud:    config:      server:
        encrypt:          enabled: false        git:          uri: https://github.com/williammian/microservices-repo
          search-paths: fornecedorms, lojams, transportadorms
          default-label: main