spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/fornecedorms?useTimezone=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect